version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      DB_USER: root
      DB_PASS: pontiac
      DB_NAME: cobagolang
      DB_HOST: mysql

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dashboard
    ports:
      - "3307:3306"